---
title: "Data Pre processing"
author: "Mangaraj & Saha" 
output: 
  html_document:
    toc: true
    toc_depth: 4 
    toc_float:
      collapsed: false
      smooth_scroll: false 
---

###Introduction:
Data preprocessing phase is an important phase in a data science project. Often we do not have full control over collection of data and the data that is given to us has irregularities such as missing values, is out of range or is not in the proper format fit for further processing. These are just a few examples of irregularities that can be found in the dataset. <br />

During the data preprocessing phase, we take care of such irregularities and make the data fit for further processing and analysis. <br />
<br />

**Selection of instances.**<br /> 
We are working on the SHIP Data, which has 4308 instances and 400 attributes to each instance, of which 578 were labelled data. Since we are do supervised learning, we are using only the labelled data. <br />
<br />
**Removal of obviously unrelated columns.**<br />
8 columns were removed because they logically do not contribute to the target variable. The list of the fields are given below: <br />


**Removal of attributes without requisite amount of data. **<br />
We removed 52 attributes because more than 5% of the values are missing. <br />

**Removal of remaining Missing Values.**

We removed the missing values for every attribute (columns). 
The attributes have either categorical values assigned to them or numeric values. 
For Categorical Data: We assigned “None” in place of the missing value. 
For Numeric Data: We used the MICE package and assign the mean of the column to the missing value. 

<br />
**At this point, the number of attributes of the dataset is 340. **
<br />
**Further steps: **
Assign categorical value to the target variable. Assign 1 if value of liver_fat is 10 or more than 10, else assign 0. 
Convert integer type values to numeric. 
<br />
**Output of this phase: imputed.rds**
